// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_Invalid   Role = 0
	Role_Leader    Role = 1
	Role_Candidate Role = 2
	Role_Follower  Role = 3
)

var Role_name = map[int32]string{
	0: "Invalid",
	1: "Leader",
	2: "Candidate",
	3: "Follower",
}

var Role_value = map[string]int32{
	"Invalid":   0,
	"Leader":    1,
	"Candidate": 2,
	"Follower":  3,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

type Entry struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type ApplyMsg struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UseSnapshot          bool     `protobuf:"varint,3,opt,name=use_snapshot,json=useSnapshot,proto3" json:"use_snapshot,omitempty"`
	Snapshot             []byte   `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyMsg) Reset()         { *m = ApplyMsg{} }
func (m *ApplyMsg) String() string { return proto.CompactTextString(m) }
func (*ApplyMsg) ProtoMessage()    {}
func (*ApplyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *ApplyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyMsg.Unmarshal(m, b)
}
func (m *ApplyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyMsg.Marshal(b, m, deterministic)
}
func (m *ApplyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyMsg.Merge(m, src)
}
func (m *ApplyMsg) XXX_Size() int {
	return xxx_messageInfo_ApplyMsg.Size(m)
}
func (m *ApplyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyMsg proto.InternalMessageInfo

func (m *ApplyMsg) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ApplyMsg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ApplyMsg) GetUseSnapshot() bool {
	if m != nil {
		return m.UseSnapshot
	}
	return false
}

func (m *ApplyMsg) GetSnapshot() []byte {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type RequestVoteRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastIndex            uint64   `protobuf:"varint,3,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	LastTerm             uint64   `protobuf:"varint,4,opt,name=last_term,json=lastTerm,proto3" json:"last_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *RequestVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRequest.Unmarshal(m, b)
}
func (m *RequestVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRequest.Marshal(b, m, deterministic)
}
func (m *RequestVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRequest.Merge(m, src)
}
func (m *RequestVoteRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRequest.Size(m)
}
func (m *RequestVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRequest proto.InternalMessageInfo

func (m *RequestVoteRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestVoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetLastIndex() uint64 {
	if m != nil {
		return m.LastIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastTerm() uint64 {
	if m != nil {
		return m.LastTerm
	}
	return 0
}

type RequestVoteReply struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Reject               bool     `protobuf:"varint,3,opt,name=reject,proto3" json:"reject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteReply) Reset()         { *m = RequestVoteReply{} }
func (m *RequestVoteReply) String() string { return proto.CompactTextString(m) }
func (*RequestVoteReply) ProtoMessage()    {}
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *RequestVoteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteReply.Unmarshal(m, b)
}
func (m *RequestVoteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteReply.Marshal(b, m, deterministic)
}
func (m *RequestVoteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteReply.Merge(m, src)
}
func (m *RequestVoteReply) XXX_Size() int {
	return xxx_messageInfo_RequestVoteReply.Size(m)
}
func (m *RequestVoteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteReply proto.InternalMessageInfo

func (m *RequestVoteReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestVoteReply) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReply) GetReject() bool {
	if m != nil {
		return m.Reject
	}
	return false
}

type AppendEntriesRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,3,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	LastLogIndex         uint64   `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	Commit               uint64   `protobuf:"varint,5,opt,name=commit,proto3" json:"commit,omitempty"`
	Entries              []*Entry `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{4}
}

func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(m, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppendEntriesRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetCommit() uint64 {
	if m != nil {
		return m.Commit
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type MatchInfo struct {
	MatchIndex           uint64   `protobuf:"varint,1,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	MatchTerm            uint64   `protobuf:"varint,2,opt,name=match_term,json=matchTerm,proto3" json:"match_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchInfo) Reset()         { *m = MatchInfo{} }
func (m *MatchInfo) String() string { return proto.CompactTextString(m) }
func (*MatchInfo) ProtoMessage()    {}
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{5}
}

func (m *MatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchInfo.Unmarshal(m, b)
}
func (m *MatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchInfo.Marshal(b, m, deterministic)
}
func (m *MatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchInfo.Merge(m, src)
}
func (m *MatchInfo) XXX_Size() int {
	return xxx_messageInfo_MatchInfo.Size(m)
}
func (m *MatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MatchInfo proto.InternalMessageInfo

func (m *MatchInfo) GetMatchIndex() uint64 {
	if m != nil {
		return m.MatchIndex
	}
	return 0
}

func (m *MatchInfo) GetMatchTerm() uint64 {
	if m != nil {
		return m.MatchTerm
	}
	return 0
}

type LogInfo struct {
	LatestIndex          uint64   `protobuf:"varint,1,opt,name=latest_index,json=latestIndex,proto3" json:"latest_index,omitempty"`
	LatestTerm           uint64   `protobuf:"varint,2,opt,name=latest_term,json=latestTerm,proto3" json:"latest_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInfo) Reset()         { *m = LogInfo{} }
func (m *LogInfo) String() string { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()    {}
func (*LogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{6}
}

func (m *LogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInfo.Unmarshal(m, b)
}
func (m *LogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInfo.Marshal(b, m, deterministic)
}
func (m *LogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfo.Merge(m, src)
}
func (m *LogInfo) XXX_Size() int {
	return xxx_messageInfo_LogInfo.Size(m)
}
func (m *LogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfo proto.InternalMessageInfo

func (m *LogInfo) GetLatestIndex() uint64 {
	if m != nil {
		return m.LatestIndex
	}
	return 0
}

func (m *LogInfo) GetLatestTerm() uint64 {
	if m != nil {
		return m.LatestTerm
	}
	return 0
}

type AppendEntriesReply struct {
	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term   uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Reject bool   `protobuf:"varint,3,opt,name=reject,proto3" json:"reject,omitempty"`
	// Types that are valid to be assigned to Info:
	//	*AppendEntriesReply_MatchInfo
	//	*AppendEntriesReply_LogInfo
	Info                 isAppendEntriesReply_Info `protobuf_oneof:"info"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AppendEntriesReply) Reset()         { *m = AppendEntriesReply{} }
func (m *AppendEntriesReply) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesReply) ProtoMessage()    {}
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{7}
}

func (m *AppendEntriesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesReply.Unmarshal(m, b)
}
func (m *AppendEntriesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesReply.Marshal(b, m, deterministic)
}
func (m *AppendEntriesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesReply.Merge(m, src)
}
func (m *AppendEntriesReply) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesReply.Size(m)
}
func (m *AppendEntriesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesReply proto.InternalMessageInfo

func (m *AppendEntriesReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppendEntriesReply) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReply) GetReject() bool {
	if m != nil {
		return m.Reject
	}
	return false
}

type isAppendEntriesReply_Info interface {
	isAppendEntriesReply_Info()
}

type AppendEntriesReply_MatchInfo struct {
	MatchInfo *MatchInfo `protobuf:"bytes,4,opt,name=match_info,json=matchInfo,proto3,oneof"`
}

type AppendEntriesReply_LogInfo struct {
	LogInfo *LogInfo `protobuf:"bytes,5,opt,name=log_info,json=logInfo,proto3,oneof"`
}

func (*AppendEntriesReply_MatchInfo) isAppendEntriesReply_Info() {}

func (*AppendEntriesReply_LogInfo) isAppendEntriesReply_Info() {}

func (m *AppendEntriesReply) GetInfo() isAppendEntriesReply_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *AppendEntriesReply) GetMatchInfo() *MatchInfo {
	if x, ok := m.GetInfo().(*AppendEntriesReply_MatchInfo); ok {
		return x.MatchInfo
	}
	return nil
}

func (m *AppendEntriesReply) GetLogInfo() *LogInfo {
	if x, ok := m.GetInfo().(*AppendEntriesReply_LogInfo); ok {
		return x.LogInfo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AppendEntriesReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AppendEntriesReply_MatchInfo)(nil),
		(*AppendEntriesReply_LogInfo)(nil),
	}
}

type InstallSnapshotRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader               uint64   `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	LastIncludeIndex     uint64   `protobuf:"varint,4,opt,name=last_include_index,json=lastIncludeIndex,proto3" json:"last_include_index,omitempty"`
	LastIncludeTerm      uint64   `protobuf:"varint,5,opt,name=last_include_term,json=lastIncludeTerm,proto3" json:"last_include_term,omitempty"`
	Offset               uint64   `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotRequest) Reset()         { *m = InstallSnapshotRequest{} }
func (m *InstallSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotRequest) ProtoMessage()    {}
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{8}
}

func (m *InstallSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotRequest.Unmarshal(m, b)
}
func (m *InstallSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotRequest.Merge(m, src)
}
func (m *InstallSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotRequest.Size(m)
}
func (m *InstallSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotRequest proto.InternalMessageInfo

func (m *InstallSnapshotRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstallSnapshotRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLastIncludeIndex() uint64 {
	if m != nil {
		return m.LastIncludeIndex
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLastIncludeTerm() uint64 {
	if m != nil {
		return m.LastIncludeTerm
	}
	return 0
}

func (m *InstallSnapshotRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *InstallSnapshotRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type InstallSnapshotReply struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Reject               bool     `protobuf:"varint,3,opt,name=reject,proto3" json:"reject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotReply) Reset()         { *m = InstallSnapshotReply{} }
func (m *InstallSnapshotReply) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotReply) ProtoMessage()    {}
func (*InstallSnapshotReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{9}
}

func (m *InstallSnapshotReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotReply.Unmarshal(m, b)
}
func (m *InstallSnapshotReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotReply.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotReply.Merge(m, src)
}
func (m *InstallSnapshotReply) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotReply.Size(m)
}
func (m *InstallSnapshotReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotReply.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotReply proto.InternalMessageInfo

func (m *InstallSnapshotReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstallSnapshotReply) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotReply) GetReject() bool {
	if m != nil {
		return m.Reject
	}
	return false
}

type ProposeRequest struct {
	Command              []byte   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposeRequest) Reset()         { *m = ProposeRequest{} }
func (m *ProposeRequest) String() string { return proto.CompactTextString(m) }
func (*ProposeRequest) ProtoMessage()    {}
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{10}
}

func (m *ProposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeRequest.Unmarshal(m, b)
}
func (m *ProposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeRequest.Marshal(b, m, deterministic)
}
func (m *ProposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeRequest.Merge(m, src)
}
func (m *ProposeRequest) XXX_Size() int {
	return xxx_messageInfo_ProposeRequest.Size(m)
}
func (m *ProposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeRequest proto.InternalMessageInfo

func (m *ProposeRequest) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type ProposeReply struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Leader               bool     `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposeReply) Reset()         { *m = ProposeReply{} }
func (m *ProposeReply) String() string { return proto.CompactTextString(m) }
func (*ProposeReply) ProtoMessage()    {}
func (*ProposeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{11}
}

func (m *ProposeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeReply.Unmarshal(m, b)
}
func (m *ProposeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeReply.Marshal(b, m, deterministic)
}
func (m *ProposeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeReply.Merge(m, src)
}
func (m *ProposeReply) XXX_Size() int {
	return xxx_messageInfo_ProposeReply.Size(m)
}
func (m *ProposeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeReply proto.InternalMessageInfo

func (m *ProposeReply) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *ProposeReply) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ProposeReply) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

func init() {
	proto.RegisterEnum("proto.Role", Role_name, Role_value)
	proto.RegisterType((*Entry)(nil), "proto.Entry")
	proto.RegisterType((*ApplyMsg)(nil), "proto.ApplyMsg")
	proto.RegisterType((*RequestVoteRequest)(nil), "proto.RequestVoteRequest")
	proto.RegisterType((*RequestVoteReply)(nil), "proto.RequestVoteReply")
	proto.RegisterType((*AppendEntriesRequest)(nil), "proto.AppendEntriesRequest")
	proto.RegisterType((*MatchInfo)(nil), "proto.MatchInfo")
	proto.RegisterType((*LogInfo)(nil), "proto.LogInfo")
	proto.RegisterType((*AppendEntriesReply)(nil), "proto.AppendEntriesReply")
	proto.RegisterType((*InstallSnapshotRequest)(nil), "proto.InstallSnapshotRequest")
	proto.RegisterType((*InstallSnapshotReply)(nil), "proto.InstallSnapshotReply")
	proto.RegisterType((*ProposeRequest)(nil), "proto.ProposeRequest")
	proto.RegisterType((*ProposeReply)(nil), "proto.ProposeReply")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b) }

var fileDescriptor_b042552c306ae59b = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0xae, 0xf3, 0xe3, 0x38, 0xe3, 0x34, 0xf5, 0x59, 0x55, 0x39, 0x6e, 0xaa, 0xaa, 0x3d, 0xd6,
	0x11, 0xaa, 0x0a, 0xaa, 0x44, 0xb8, 0xe5, 0xa6, 0x20, 0xa0, 0x51, 0x1b, 0x54, 0x99, 0x8a, 0xdb,
	0x68, 0x89, 0xd7, 0xad, 0xd1, 0xda, 0x6b, 0xec, 0x0d, 0x90, 0x37, 0xe3, 0x01, 0x78, 0x0a, 0xee,
	0x78, 0x13, 0xb4, 0xb3, 0x6b, 0x93, 0xb4, 0xa9, 0xd4, 0xaa, 0x57, 0xf6, 0x37, 0xdf, 0xec, 0xcc,
	0x7c, 0xb3, 0xb3, 0x03, 0x50, 0xd0, 0x58, 0x1e, 0xe7, 0x85, 0x90, 0x82, 0xb4, 0xf1, 0x13, 0x9c,
	0x41, 0xfb, 0x4d, 0x26, 0x8b, 0x05, 0x21, 0xd0, 0x92, 0xac, 0x48, 0x7d, 0xeb, 0xc0, 0x3a, 0x6c,
	0x85, 0xf8, 0x4f, 0xb6, 0xa1, 0x9d, 0x64, 0x11, 0xfb, 0xee, 0x37, 0xd0, 0xa8, 0x01, 0xf1, 0xa1,
	0x33, 0x13, 0x99, 0x64, 0x99, 0xf4, 0x9b, 0x07, 0xd6, 0x61, 0x2f, 0xac, 0x60, 0xb0, 0x00, 0xe7,
	0x24, 0xcf, 0xf9, 0x62, 0x52, 0x5e, 0xfd, 0x3d, 0x6b, 0xdd, 0x71, 0xb6, 0xb1, 0x72, 0x96, 0xfc,
	0x07, 0xbd, 0x79, 0xc9, 0xa6, 0x65, 0x46, 0xf3, 0xf2, 0x5a, 0xe8, 0xd0, 0x4e, 0xe8, 0xce, 0x4b,
	0xf6, 0xc1, 0x98, 0xc8, 0x10, 0x9c, 0x9a, 0x6e, 0xe1, 0xe9, 0x1a, 0x07, 0x12, 0x48, 0xc8, 0xbe,
	0xcc, 0x59, 0x29, 0x3f, 0x0a, 0xc9, 0xcc, 0x2f, 0xe9, 0x43, 0x23, 0x89, 0x4c, 0x05, 0x8d, 0x24,
	0xaa, 0x45, 0x36, 0x96, 0x44, 0xee, 0x01, 0x70, 0x5a, 0xca, 0xa9, 0xae, 0xb6, 0x89, 0x4c, 0x57,
	0x59, 0xc6, 0x58, 0xf1, 0x2e, 0x20, 0x98, 0xe2, 0xb9, 0x16, 0xb2, 0x8e, 0x32, 0x5c, 0xb2, 0x22,
	0x0d, 0xde, 0x83, 0xb7, 0x92, 0x35, 0xe7, 0x8b, 0x7b, 0xe5, 0x1c, 0x80, 0x5d, 0xb0, 0xcf, 0x6c,
	0x56, 0xc9, 0x34, 0x28, 0xf8, 0x69, 0xc1, 0xf6, 0x49, 0x9e, 0xb3, 0x2c, 0x52, 0x97, 0x92, 0xb0,
	0xf2, 0x21, 0x42, 0x02, 0xd8, 0xc4, 0x4a, 0xb9, 0xb8, 0xd2, 0xd5, 0x6a, 0x2d, 0xae, 0x32, 0x9e,
	0x8b, 0x2b, 0x55, 0x30, 0xf9, 0x1f, 0xfa, 0xb5, 0x8f, 0x16, 0xac, 0x25, 0xf5, 0x8c, 0x93, 0xd6,
	0x3c, 0x00, 0x7b, 0x26, 0xd2, 0x34, 0x91, 0x7e, 0x1b, 0x59, 0x83, 0xc8, 0x13, 0xe8, 0x30, 0x5d,
	0x97, 0x6f, 0x1f, 0x34, 0x0f, 0xdd, 0x51, 0x4f, 0x0f, 0xd3, 0x31, 0x8e, 0x50, 0x58, 0x91, 0xc1,
	0x19, 0x74, 0x27, 0x54, 0xce, 0xae, 0xc7, 0x59, 0x2c, 0xc8, 0x3e, 0xb8, 0xa9, 0x02, 0xd3, 0xe5,
	0x71, 0x80, 0x54, 0xf3, 0x2a, 0xdb, 0x1e, 0x68, 0x34, 0x5d, 0x52, 0xd4, 0x45, 0x0b, 0xf6, 0x78,
	0x02, 0x1d, 0x2c, 0x2c, 0x16, 0x6a, 0x46, 0x38, 0x95, 0xac, 0xbe, 0x2c, 0xab, 0x12, 0xa8, 0x6c,
	0x3a, 0xd8, 0x3e, 0x18, 0xb8, 0x1c, 0x0d, 0xb4, 0x09, 0xc3, 0xfd, 0xb0, 0x80, 0xdc, 0x68, 0xf1,
	0x23, 0x6f, 0x8d, 0x3c, 0xaf, 0x04, 0x24, 0x59, 0x2c, 0xb0, 0xa1, 0xee, 0xc8, 0x33, 0x9d, 0xa9,
	0xfb, 0x70, 0xba, 0x61, 0x44, 0xa1, 0x92, 0xa7, 0xe0, 0xe8, 0x2b, 0x88, 0x05, 0xf6, 0xd8, 0x1d,
	0xf5, 0xcd, 0x01, 0xa3, 0xf5, 0x74, 0x23, 0xec, 0x70, 0xfd, 0xfb, 0xca, 0x86, 0x96, 0x72, 0x0c,
	0x7e, 0x59, 0x30, 0x18, 0x67, 0xa5, 0xa4, 0x9c, 0x57, 0x6f, 0xe2, 0x21, 0xf3, 0x31, 0x00, 0x9b,
	0x33, 0x1a, 0xb1, 0xc2, 0x0c, 0x86, 0x41, 0xe4, 0x19, 0x10, 0xf3, 0x00, 0x66, 0x7c, 0x1e, 0xb1,
	0x95, 0xb9, 0xf0, 0xf4, 0x43, 0x40, 0x42, 0x37, 0xf8, 0x08, 0xfe, 0x59, 0xf1, 0xc6, 0x34, 0x7a,
	0x4c, 0xb6, 0x96, 0x9c, 0x2f, 0x4d, 0x46, 0x11, 0xc7, 0x25, 0x93, 0xbe, 0xad, 0x33, 0x6a, 0xa4,
	0xaa, 0x8b, 0xa8, 0xa4, 0x7e, 0x07, 0x1f, 0x31, 0xfe, 0x07, 0x21, 0x6c, 0xdf, 0xd2, 0xf6, 0xd8,
	0xe7, 0x74, 0x04, 0xfd, 0x8b, 0x42, 0xe4, 0xa2, 0xac, 0x17, 0x02, 0xee, 0x9f, 0x34, 0xa5, 0x99,
	0x0e, 0x89, 0xfb, 0x07, 0x61, 0x70, 0x01, 0xbd, 0xda, 0x57, 0xe5, 0xbd, 0xff, 0x3e, 0x5c, 0xed,
	0xab, 0x53, 0xf5, 0xf5, 0xe8, 0x25, 0xb4, 0x42, 0xc1, 0x19, 0x71, 0xa1, 0x33, 0xce, 0xbe, 0x52,
	0x9e, 0x44, 0xde, 0x06, 0x01, 0xb0, 0xcf, 0x91, 0xf6, 0x2c, 0xb2, 0x09, 0xdd, 0xd7, 0x34, 0x8b,
	0x92, 0x88, 0x4a, 0xe6, 0x35, 0x48, 0x0f, 0x9c, 0xb7, 0x82, 0x73, 0xf1, 0x8d, 0x15, 0x5e, 0x73,
	0xf4, 0xdb, 0x82, 0x56, 0x48, 0x63, 0x49, 0x4e, 0xc0, 0x5d, 0xda, 0x31, 0x64, 0xc7, 0xcc, 0xc9,
	0xed, 0x6d, 0x37, 0xfc, 0x77, 0x1d, 0xa5, 0xb4, 0xbc, 0x83, 0xcd, 0x95, 0x91, 0x27, 0xbb, 0xc6,
	0x73, 0xdd, 0xae, 0x19, 0xee, 0xac, 0x27, 0x55, 0xa0, 0x09, 0x6c, 0xdd, 0xb8, 0x24, 0xb2, 0x67,
	0xbc, 0xd7, 0x0f, 0xe6, 0x70, 0xf7, 0x2e, 0x3a, 0xe7, 0x8b, 0x4f, 0x36, 0x72, 0x2f, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x8f, 0xa4, 0x34, 0x5f, 0x98, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteReply, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesReply, error)
	InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotReply, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteReply, error) {
	out := new(RequestVoteReply)
	err := c.cc.Invoke(ctx, "/proto.Raft/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesReply, error) {
	out := new(AppendEntriesReply)
	err := c.cc.Invoke(ctx, "/proto.Raft/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotReply, error) {
	out := new(InstallSnapshotReply)
	err := c.cc.Invoke(ctx, "/proto.Raft/InstallSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteReply, error)
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesReply, error)
	InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotReply, error)
}

// UnimplementedRaftServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (*UnimplementedRaftServer) RequestVote(ctx context.Context, req *RequestVoteRequest) (*RequestVoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (*UnimplementedRaftServer) AppendEntries(ctx context.Context, req *AppendEntriesRequest) (*AppendEntriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}
func (*UnimplementedRaftServer) InstallSnapshot(ctx context.Context, req *InstallSnapshotRequest) (*InstallSnapshotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallSnapshot not implemented")
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_InstallSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).InstallSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/InstallSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).InstallSnapshot(ctx, req.(*InstallSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "InstallSnapshot",
			Handler:    _Raft_InstallSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
