// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shardkv.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{0}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutReply) Reset()         { *m = PutReply{} }
func (m *PutReply) String() string { return proto.CompactTextString(m) }
func (*PutReply) ProtoMessage()    {}
func (*PutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{1}
}

func (m *PutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutReply.Unmarshal(m, b)
}
func (m *PutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutReply.Marshal(b, m, deterministic)
}
func (m *PutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutReply.Merge(m, src)
}
func (m *PutReply) XXX_Size() int {
	return xxx_messageInfo_PutReply.Size(m)
}
func (m *PutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PutReply.DiscardUnknown(m)
}

var xxx_messageInfo_PutReply proto.InternalMessageInfo

type AppendRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendRequest) Reset()         { *m = AppendRequest{} }
func (m *AppendRequest) String() string { return proto.CompactTextString(m) }
func (*AppendRequest) ProtoMessage()    {}
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{2}
}

func (m *AppendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendRequest.Unmarshal(m, b)
}
func (m *AppendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendRequest.Marshal(b, m, deterministic)
}
func (m *AppendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendRequest.Merge(m, src)
}
func (m *AppendRequest) XXX_Size() int {
	return xxx_messageInfo_AppendRequest.Size(m)
}
func (m *AppendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendRequest proto.InternalMessageInfo

func (m *AppendRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AppendRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AppendReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendReply) Reset()         { *m = AppendReply{} }
func (m *AppendReply) String() string { return proto.CompactTextString(m) }
func (*AppendReply) ProtoMessage()    {}
func (*AppendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{3}
}

func (m *AppendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendReply.Unmarshal(m, b)
}
func (m *AppendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendReply.Marshal(b, m, deterministic)
}
func (m *AppendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendReply.Merge(m, src)
}
func (m *AppendReply) XXX_Size() int {
	return xxx_messageInfo_AppendReply.Size(m)
}
func (m *AppendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppendReply proto.InternalMessageInfo

type DeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReply) Reset()         { *m = DeleteReply{} }
func (m *DeleteReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()    {}
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{5}
}

func (m *DeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReply.Unmarshal(m, b)
}
func (m *DeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReply.Marshal(b, m, deterministic)
}
func (m *DeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReply.Merge(m, src)
}
func (m *DeleteReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReply.Size(m)
}
func (m *DeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReply proto.InternalMessageInfo

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{6}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetReply struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{7}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MigrateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateRequest) Reset()         { *m = MigrateRequest{} }
func (m *MigrateRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateRequest) ProtoMessage()    {}
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{8}
}

func (m *MigrateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateRequest.Unmarshal(m, b)
}
func (m *MigrateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateRequest.Marshal(b, m, deterministic)
}
func (m *MigrateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateRequest.Merge(m, src)
}
func (m *MigrateRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateRequest.Size(m)
}
func (m *MigrateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateRequest proto.InternalMessageInfo

type MigrateReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateReply) Reset()         { *m = MigrateReply{} }
func (m *MigrateReply) String() string { return proto.CompactTextString(m) }
func (*MigrateReply) ProtoMessage()    {}
func (*MigrateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e390eaad9f89b9c, []int{9}
}

func (m *MigrateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateReply.Unmarshal(m, b)
}
func (m *MigrateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateReply.Marshal(b, m, deterministic)
}
func (m *MigrateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateReply.Merge(m, src)
}
func (m *MigrateReply) XXX_Size() int {
	return xxx_messageInfo_MigrateReply.Size(m)
}
func (m *MigrateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateReply.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PutRequest)(nil), "proto.PutRequest")
	proto.RegisterType((*PutReply)(nil), "proto.PutReply")
	proto.RegisterType((*AppendRequest)(nil), "proto.AppendRequest")
	proto.RegisterType((*AppendReply)(nil), "proto.AppendReply")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "proto.DeleteReply")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetReply)(nil), "proto.GetReply")
	proto.RegisterType((*MigrateRequest)(nil), "proto.MigrateRequest")
	proto.RegisterType((*MigrateReply)(nil), "proto.MigrateReply")
}

func init() { proto.RegisterFile("shardkv.proto", fileDescriptor_7e390eaad9f89b9c) }

var fileDescriptor_7e390eaad9f89b9c = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0xa5, 0x7f, 0x7c, 0x9a, 0x5a, 0xc7, 0x0a, 0x25, 0x07, 0xa9, 0x7b, 0xd2, 0x4b,
	0x0f, 0x55, 0xf1, 0x2c, 0x08, 0x3d, 0x88, 0x50, 0x2a, 0x78, 0x8f, 0x74, 0x50, 0xe9, 0x62, 0xd7,
	0x74, 0x53, 0xc8, 0x97, 0x17, 0xd9, 0xcd, 0x76, 0xb3, 0x29, 0xe4, 0xd0, 0x53, 0x92, 0x37, 0x79,
	0x33, 0xef, 0xfd, 0x10, 0x6f, 0xbe, 0xd2, 0x6c, 0xb9, 0xda, 0x4e, 0x54, 0xb6, 0xd6, 0x6b, 0x6a,
	0xdb, 0x87, 0xb8, 0x07, 0xe6, 0xb9, 0x5e, 0xf0, 0x6f, 0xce, 0x1b, 0x4d, 0x03, 0xb4, 0x56, 0x5c,
	0x8c, 0xa2, 0x71, 0x74, 0x73, 0xbc, 0x30, 0xaf, 0x34, 0x44, 0x7b, 0x9b, 0xca, 0x9c, 0x47, 0x47,
	0x56, 0x2b, 0x3f, 0x04, 0xd0, 0xb3, 0x2e, 0x25, 0x0b, 0xf1, 0x88, 0xf8, 0x49, 0x29, 0xfe, 0x59,
	0x1e, 0xba, 0x24, 0xc6, 0xc9, 0xce, 0x68, 0xf6, 0x5c, 0x23, 0x7e, 0x66, 0xc9, 0x9a, 0x1b, 0xf7,
	0x18, 0xc7, 0xee, 0x17, 0xe3, 0xb8, 0x02, 0x66, 0xdc, 0x9c, 0x5d, 0x8c, 0xd1, 0xb3, 0x73, 0x25,
	0x83, 0x08, 0x51, 0x18, 0x61, 0x80, 0xfe, 0xeb, 0xf7, 0x67, 0x96, 0xfa, 0xa3, 0xa2, 0x8f, 0x53,
	0xaf, 0x28, 0x59, 0x4c, 0xff, 0x22, 0x74, 0xdf, 0x0c, 0xb8, 0x97, 0x77, 0xba, 0x45, 0x6b, 0x9e,
	0x6b, 0x3a, 0x2f, 0x09, 0x4e, 0x2a, 0x6e, 0xc9, 0x59, 0x28, 0x99, 0x73, 0x53, 0x74, 0xca, 0x6e,
	0x34, 0x74, 0xa3, 0x1a, 0xa3, 0x84, 0xf6, 0x54, 0xe7, 0x29, 0xdb, 0x79, 0x4f, 0x8d, 0x87, 0xf7,
	0x04, 0x08, 0x4c, 0xa4, 0x19, 0x57, 0x91, 0x2a, 0x1c, 0x3e, 0x92, 0x27, 0xf0, 0x80, 0xae, 0x6b,
	0x46, 0x97, 0x6e, 0x56, 0xef, 0x9e, 0x5c, 0xec, 0xcb, 0x4a, 0x16, 0x1f, 0x1d, 0xab, 0xdd, 0xfd,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x5d, 0x13, 0x1d, 0x3f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShardKVClient is the client API for ShardKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShardKVClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendReply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateReply, error)
}

type shardKVClient struct {
	cc *grpc.ClientConn
}

func NewShardKVClient(cc *grpc.ClientConn) ShardKVClient {
	return &shardKVClient{cc}
}

func (c *shardKVClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	out := new(PutReply)
	err := c.cc.Invoke(ctx, "/proto.ShardKV/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendReply, error) {
	out := new(AppendReply)
	err := c.cc.Invoke(ctx, "/proto.ShardKV/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, "/proto.ShardKV/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/proto.ShardKV/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateReply, error) {
	out := new(MigrateReply)
	err := c.cc.Invoke(ctx, "/proto.ShardKV/Migrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardKVServer is the server API for ShardKV service.
type ShardKVServer interface {
	Put(context.Context, *PutRequest) (*PutReply, error)
	Append(context.Context, *AppendRequest) (*AppendReply, error)
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
	Migrate(context.Context, *MigrateRequest) (*MigrateReply, error)
}

// UnimplementedShardKVServer can be embedded to have forward compatible implementations.
type UnimplementedShardKVServer struct {
}

func (*UnimplementedShardKVServer) Put(ctx context.Context, req *PutRequest) (*PutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedShardKVServer) Append(ctx context.Context, req *AppendRequest) (*AppendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (*UnimplementedShardKVServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedShardKVServer) Get(ctx context.Context, req *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedShardKVServer) Migrate(ctx context.Context, req *MigrateRequest) (*MigrateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}

func RegisterShardKVServer(s *grpc.Server, srv ShardKVServer) {
	s.RegisterService(&_ShardKV_serviceDesc, srv)
}

func _ShardKV_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShardKV/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShardKV/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShardKV/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShardKV/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShardKV/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShardKV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShardKV",
	HandlerType: (*ShardKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _ShardKV_Put_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _ShardKV_Append_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ShardKV_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ShardKV_Get_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _ShardKV_Migrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shardkv.proto",
}
